### PR TITLE
Initialize Github Action

### PR DESCRIPTION
**Pull request by DatLam25**

### CODE REVIEW

**Comment by DatLam25** [comment]
I'm sorry that the commit history is terrible on this pull request. I will squash the commits before merging to main though.

**Comment by Dillonsd** [comment]
Do all these changes belong in this PR? A bunch seem unrelated to Github Actions

**Comment by DatLam25** [comment]
This pr combines updating deprecated code with adding Github actions since we need both for Github Action to run.

**Comment by Dillonsd** [comment]
Github Actions looks good. Will let @Hesham-E review the Hermes code.

**Pull request merged**
